theme                    : jekyll-theme-slate
locale                   : "zh-TW"  # 自己的地區
title                    : "PolloChang's Blog"  # 網站的名稱
title_separator          : "-"
subtitle                 : "Linux 筆記" # 子標題，位於網站名稱下方
name                     : "PolloChang"
description              : "An amazing website."
# url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
# baseurl                  : # the subpath of your site, e.g. "/blog"
# repository               : "KTingLee/KTingLee.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

relative_links:
  enabled:     true
  collections: false